name: bookdown

on:
  push:
    branches: master


jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' #issues with installing MASS package if use 4.3.0+
          #https://stackoverflow.com/questions/76469848/compilation-error-building-archive-version-of-mass-on-macos

      - name: Install pandoc 
        run: |
          brew install pandoc

# - name: Cache Renv packages
      #   uses: actions/cache@v1
      #   with:
      #     path: $HOME/.local/share/renv
      #     key: r-${{ hashFiles('renv.lock') }}
      #     restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
          
      # - name: Install packages
      #   run: |
      #     R -e 'install.packages("renv")'
      #     R -e 'renv::restore()'
        
      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _book # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
